### ISSUE TITLE
mount /one-container/resolv.conf:/etc/resolv.conf: not a directory

### ISSUE THREAD

**Issue by unclamped** [pluim003/docker-pihole-unbound#14]
Hello, when trying to install the `one-container` docker-compose with Portainer on my Raspberry Pi 4, I got the following error:
`failed to deploy a stack: Network pihole-unbound_default  Creating Network pihole-unbound_default  Created Container pihole-unbound  Creating Container pihole-unbound  Created Container pihole-unbound  Starting Error response from daemon: failed to create shim task: OCI runtime  create failed: runc create failed: unable to start container process:  error during container init: error mounting  "/data/compose/26/one-container/resolv.conf" to rootfs at  "/etc/resolv.conf": mount  /data/compose/26/one-container/resolv.conf:/etc/resolv.conf (via  /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`
I'm not really sure as to what this error could mean, but is it trying to say that the compose is attempting to mount a directory instead of the resolv.conf file?

**Comment by pluim003** [comment]
How does your docker-compose.yml look like? I have seen errors before like mapping file on a directory.

**Comment by unclamped** [comment]
> How does your docker-compose.yml look like? I have seen errors before like mapping file on a directory.

I'm directly specifying the remote location of this project's .yaml compose. All my remaining changes are either for Portainer's own update system (to check for updates on the compose each 5 mins) and my env variables which I can set from the web UI

**Comment by pluim003** [comment]
I'm not familiar with pasting stuff directly in Portainer. I start it up through the prompt. Can you still show me what the contents are which you paste in Portainer. Note that there are some issues (mentioned in the readme) when using portainer.
What happens if you use the original repository by Chris Crowe where this is a fork from?

**Comment by unclamped** [comment]
> I'm not familiar with pasting stuff directly in Portainer. I start it up through the prompt. Can you still show me what the contents are which you paste in Portainer. Note that there are some issues (mentioned in the readme) when using portainer. What happens if you use the original repository by Chris Crowe where this is a fork from?

The Portainer issues listed on the docs are no longer a thing, they don't occur in either Chris' project or in this one (I guess?) 
![image](https://user-images.githubusercontent.com/104658278/219724764-3bbb7b6f-3382-4a8a-a6a2-5197a34820de.png)
![image](https://user-images.githubusercontent.com/104658278/219725099-75920dbc-4f16-470a-805f-2016bdde256a.png)

**Comment by unclamped** [comment]
oh wait, the repo's folder structure changed. one sec

**Comment by unclamped** [comment]
updated the Compose path, same issue though

**Comment by mariomare22** [comment]
it's enough to create an empty file with `touch <filename>` ; docker is not the best at creating files; it's used to directories

**Comment by pluim003** [comment]
I tried the Portainer-thing, but indeed it throws an error:

![afbeelding](https://user-images.githubusercontent.com/67138922/219755860-e3131754-cccf-4a2b-962e-6ed0ffa34354.png)

I tried by adding resolv.conf to the repository, but that doesn't help. I don't know actually where Portainer will look for it when trying to map.

Tried the following:

![afbeelding](https://user-images.githubusercontent.com/67138922/219759177-48897f23-131b-41f0-b8ce-dbc5bb0d7ef4.png)

And /home/pi/pi-hole exists but I get the error:

![afbeelding](https://user-images.githubusercontent.com/67138922/219759297-e7b3c1a4-7b68-4ffd-9c54-291f8626a756.png)

Could you try to save the docker-compose.yaml-file locally and start it up through docker-compose up -d ?

Frankly at the moment I don't know how to solve this and it seems also the original repo has the same issue. I was searching but I can't find a solution yet. This needs deeper digging.

**Comment by unclamped** [comment]
Chris' project works just fine, I was able to deploy it today just by changing the git URL while still keeping all my env variables from this project (had to change the WEB_PORT one to PIHOLE_WEBPORT, but that shouldn't be the cause of the issue either way).
As to trying to run the .yaml from the terminal directly without Portainer, the issue persists:
```ducky@raspi:ducky/pihole-unbound | sudo docker compose up
[+] Running 5/5
 ⠿ Network pihole-unbound_default       Created                                                                                                   0.1s
 ⠿ Volume "pihole-unbound_etc_dnsmasq"  Created                                                                                                   0.0s
 ⠿ Volume "pihole-unbound_etc_unbound"  Created                                                                                                   0.0s
 ⠿ Volume "pihole-unbound_etc_pihole"   Created                                                                                                   0.0s
 ⠿ Container pihole-unbound             Created                                                                                                   1.4s
Attaching to pihole-unbound
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/ducky/pihole-unbound/resolv.conf" to rootfs at "/etc/resolv.conf": mount /home/ducky/pihole-unbound/resolv.conf:/etc/resolv.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type```
Doing what Mario suggested about doing `touch` first seems to solve the issue. I had to first `rm -rf` the resolv.conf directory that was created, and then do `touch resolv.conf` in the compose folder, and that seemed to work. Doing the same for the hosts file in Mario's repo works too.

**Comment by unclamped** [comment]
on another topic, now I'm wondering, what's different between Mario's repo and yours? Both seem to do the same thing, DoT and updated dependencies

**Comment by mariomare22** [comment]
No idea what the differences are.
I only added to the original container from Chris 2 things
- the DoT in the pi-hole config for forward-zone to cloudflare DoT
- the download of the root.hint for unbound

Plus i have tuned the auto build on base image update

**Comment by pluim003** [comment]
@unclamped Hmm... I checked Chris's docker-compose.yaml and that doesn't contain a mapping to /etc/resolv.conf and in the one from Mario it has a different mapping including $pwd . 

With respect to the differences between mine and Mario's: I forked Chris's repo over half a year ago and modified it to use a more recent version of Unbound and added some small tools further on. And a few days ago I added the DoT used by Mario. I'll check if I can check what happens if I cut out the mapping to resolv.conf.

**Comment by pluim003** [comment]
Update: I put it in dev-branch. I was able to start it (ofcourse I missed some more mappings, or due to the new mappings my current configs weren't being used). Only difference is that etc.resolv.conf looks like:

root@0d2a9400af8e:/etc# cat resolv.conf
nameserver 127.0.0.11
options ndots:0

whereas the one it normally uses and grabbed from my system looks like:

root@pihole:/etc# cat resolv.conf
nameserver 127.0.0.1
nameserver 1.1.1.1
options ndots:0

Described in https://discourse.pi-hole.net/t/127-0-0-11-in-etc-resolv-conf/22450 . I'm wondering if this will work as expected if I leave the mapping to /etc/resolv.conf out. 

@unclamped Is the docker-compose.yaml from @mariomare22 working when you paste it in Portainer?

**Comment by mariomare22** [comment]
This is the compose file I use in portainer:

```
version: '3.0'

services:
  pihole:
    container_name: pihole
    image: ghcr.io/mariomare22/docker-pihole-unbound:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${PIHOLE_WEBPORT:-80}:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80

    environment:
      - PUID=1000
      - PGID=1000
      - FTLCONF_LOCAL_IPV4=${FTLCONF_LOCAL_IPV4}
      - TZ=${TZ}
      - WEBPASSWORD=${WEBPASSWORD}
      - REV_SERVER=${REV_SERVER:-false}
      - REV_SERVER_TARGET=${REV_SERVER_TARGET}
      - REV_SERVER_DOMAIN=${REV_SERVER_DOMAIN}
      - REV_SERVER_CIDR=${REV_SERVER_CIDR}
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC=${DNSSEC}
      - DNSMASQ_LISTENING=single
    volumes:
      - /home/mario/config/pihole/etc_pihole-unbound:/etc/pihole:rw
      - /home/mario/config/pihole/etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
      - /home/mario/config/pihole/etc_unbound:/etc/unbound/unbound.conf.d/:rw
      - /home/mario/config/pihole/hosts:/etc/hosts:rw
    restart: unless-stopped
    ```
    
    and this is the .env file, pasted into portainer as well

```
FTLCONF_LOCAL_IPV4=10.22.10.2
TZ=Europe/Rome
REV_SERVER=true
REV_SERVER_DOMAIN=local
REV_SERVER_TARGET=10.22.10.1
REV_SERVER_CIDR=10.22.10.0/27
HOSTNAME=server
DOMAIN_NAME=server.local
PIHOLE_WEBPORT=3022
FTLCONF_CHECK_LOAD=false
WEBPASSWORD=mario
DNSSEC=true
```
