### ISSUE TITLE
Unbound could not open /etc/unbound/unbound.conf

### ISSUE THREAD

**Issue by zenzip** [pluim003/docker-pihole-unbound#21]
Trying to deploy the last container version, using docker compose but unbound fail to start:

`Starting unbound
[1680123640] unbound-checkconf[386:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1680123640] unbound[391:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1680123640] unbound[391:0] warning: Continuing with default config settings
[1680123640] unbound[391:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1680123640] unbound[391:0] fatal error: could not open ports`

**Comment by zenzip** [comment]
Issue apper when trying to use bind mounts folder in place of volumes. This is strange cause bind mounted folders exists and has the right permissions.

**Comment by pluim003** [comment]
I know see this. Did you get this with the latest release? How does your docker-compose.yml look like?

**Comment by zenzip** [comment]
Yes closed by mistake. 
Happening with last version and this is how my compose look:

```version: '3.0'

services:
  pihole:
    container_name: pihole-unbound
    image: pluim003/pihole-unbound:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - ${WEB_PORT}:80/tcp
      - 53:53/tcp
      - 53:53/udp
      # - 5335:5335/tcp # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    environment:
      FTLCONF_LOCAL_IPV4: ${FTLCONF_LOCAL_IPV4}
      TZ: Europe/Rome
      WEBPASSWORD: ${WEBPASSWORD}
      REV_SERVER: true
      REV_SERVER_DOMAIN: local
      REV_SERVER_TARGET: ${REV_SERVER_TARGET}
      REV_SERVER_CIDR: ${REV_SERVER_CIDR}
      PIHOLE_DNS_: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNSSEC: "true" # Enable DNSSEC
      DNSMASQ_LISTENING: single
    volumes:
      - /docker-data/pihole-unbound/pihole:/etc/pihole:rw
      - /docker-data/pihole-unbound/dnsmasq.d:/etc/dnsmasq.d:rw
      - /docker-data/pihole-unbound/unbound:/etc/unbound:rw
      - /etc/resolv.conf:/etc/resolv.conf
    restart: unless-stopped```

I'm trying to use bind mounts in place of volumes because using the volume as for your template, if I want to edit/re-create the container through Portainer I get this error and I think that with bind volumes this can be solved:

`Duplicate mount point: /etc/pihole`

**Comment by pluim003** [comment]
Aha. Can it be that the container is still running when you try to start it? That might cause the duplicate mount point.

**Comment by zenzip** [comment]
> Aha. Can it be that the container is still running when you try to start it? That might cause the duplicate mount point.

Nope, error happens even with stopped container :( It's very strange.

This is the compose in the version that use the volumes (obv almost identical to the above one that use bind mounts):
```
`version: '3.0'

volumes:
  etc_pihole:
  etc_dnsmasq:
  etc_unbound:
  
services:
  pihole:
    container_name: pihole-unbound
    image: pluim003/pihole-unbound:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - ${WEB_PORT}:80/tcp
      - 53:53/tcp
      - 53:53/udp
      # - 5335:5335/tcp # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    environment:
      FTLCONF_LOCAL_IPV4: ${FTLCONF_LOCAL_IPV4}
      TZ: Europe/Rome
      WEBPASSWORD: ${WEBPASSWORD}
      REV_SERVER: true
      REV_SERVER_DOMAIN: local
      REV_SERVER_TARGET: ${REV_SERVER_TARGET}
      REV_SERVER_CIDR: ${REV_SERVER_CIDR}
      PIHOLE_DNS_: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNSSEC: "true" # Enable DNSSEC
      DNSMASQ_LISTENING: single
    volumes:
      - etc_pihole:/etc/pihole:rw
      - etc_dnsmasq:/etc/dnsmasq.d:rw
      - etc_unbound:/etc/unbound:rw
      - /etc/resolv.conf:/etc/resolv.conf
    restart: unless-stopped

**Comment by pluim003** [comment]
Hmm... something similar happens in https://www.reddit.com/r/portainer/comments/vrvbrx/docker_volumes_problem_duplicate_mount_point/ Does it complain about another mount point if you change the sequence in your docker-compose.yaml-file? 
Could you also run docker-compose --verbose up

**Comment by zenzip** [comment]
Thanks I'll take a look.
It's strange becasue I run a dozen of container and the issue appear only with this pihole-unbound.

Thanks again for the support, I'll keep you updated.

_Bonus:_
A docker-compose file with bind mounts in place of docker volumes can be useful for several reason :)

**Comment by zenzip** [comment]
up, any idea ? I've tried with several settings, but didin't find a solution.
@pluim003 how are you actually update the container without getting this issue ?

```version: '3.0'

volumes:
  etc_pihole:
  etc_dnsmasq:
  etc_unbound:

services:
  pihole:
    container_name: pihole
    image: pluim003/pihole-unbound:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - ${PIHOLE_WEBPORT:-80}:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
      - 53:53/tcp
      - 53:53/udp
      # - 5335:5335/tcp # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    environment:
      FTLCONF_LOCAL_IPV4: ${FTLCONF_LOCAL_IPV4}
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      REV_SERVER: ${REV_SERVER:-false}
      REV_SERVER_TARGET: ${REV_SERVER_TARGET}
      REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
      REV_SERVER_CIDR: ${REV_SERVER_CIDR}
      PIHOLE_DNS_: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNSSEC: ${DNSSEC:-false} # Enable DNSSEC
      DNSMASQ_LISTENING: single
    volumes:
      - etc_pihole:/etc/pihole:rw
      - etc_dnsmasq:/etc/dnsmasq.d:rw
      - etc_unbound:/etc/unbound:rw
      - /etc/resolv.conf:/etc/resolv.conf
    restart: unless-stopped```

**Comment by pluim003** [comment]
@zenzip  what happens if you don't use the volume etc_unbound? I would guess it will use the default unbound.conf. Or is it then also missing? If so then I'll need to check my Dockerfile to see what's going wrong. On my side everything is running fine.

**Comment by pluim003** [comment]
Frankly I don't know what can go wrong. How are you updating the container? I use a script like this:

```
pi@raspberrypi4:~/pi-hole $ cat upg_pihole_nightly.sh
#!/bin/bash
VANDAAG=$(date +"%Y%m%d")

cd $(dirname $0)

current_pihole_nightly="$(docker inspect pluim003/pihole-unbound:nightly  | grep Created)"

docker pull pluim003/pihole-unbound:nightly

pulled_pihole_nightly="$(docker inspect pluim003/pihole-unbound:nightly  | grep Created)"

if [[ "${pulled_pihole_nightly}" > "${current_pihole_nightly}" ]];
then echo "There is a new Pihole-nightly, recreating the Pihole-Unbound-nightly"
     cp docker-compose.nightly docker-compose.yaml
     docker container stop $(docker container ls -q --filter name=pihole-unbound*)
# docker rename pihole-unbound pihole-unbound_${VANDAAG}_$(docker container ls -q --filter name=pihole-unbound*)

/usr/local/bin/docker-compose up -d
fi
```

And my docker-compose looks like:

```
pi@raspberrypi4:~/pi-hole $ cat docker-compose.yaml
version: '3.0'

volumes:
  etc_pihole:
  etc_dnsmasq:
  etc_unbound:
  log_pihole:
  log_unbound:
  log_lighttpd:
  resolv.conf:
  usr_pihole_lists:
  ssh:

services:
  pihole:
    container_name: pihole-unbound
    image: pluim003/pihole-unbound:nightly
    privileged: true
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - ${WEB_PORT}:80/tcp
      - 53:53/tcp
      - 53:53/udp
      # - 80:80/tcp
      - 5335:5335/tcp # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    environment:
#      network_mode: host
      FTLCONF_LOCAL_IPV4: ${FTLCONF_LOCAL_IPV4}
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
#      WEB_UID: ${WEB_UID}
#      WEB_GID: ${WEB_GID}
      REV_SERVER: ${REV_SERVER}
      REV_SERVER_TARGET: ${REV_SERVER_TARGET}
      REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
      REV_SERVER_CIDR: ${REV_SERVER_CIDR}
      PIHOLE_DNS_: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNSSEC: ${DNSSEC}
      DNSMASQ_LISTENING: single
      VIRTUAL_HOST: ${VIRTUAL_HOST}
#      DNS1: ${DNS1}
      FTLCONF_MAXDBDAYS: ${FTLCONF_MAXDBDAYS}
    volumes:
      - etc_pihole:/etc/pihole:rw
      - etc_dnsmasq:/etc/dnsmasq.d:rw
      - etc_unbound:/etc/unbound:rw
      - log_pihole:/var/log/pihole:rw
      - log_unbound:/var/log/unbound:rw
      - log_lighttpd:/var/log/lighttpd:rw
#      - ./resolv.conf:/etc/resolv.conf
      - usr_pihole_lists:/usr/local/bin/my-pihole-lists
      - ssh:/root/.ssh
#      - /sys/fs/cgroup:/sys/fs/cgroup
    restart: unless-stopped
```

It's recreating nicely every morning a new container. So frankly I'm a bit lost.
