### ISSUE TITLE
Docker-compose one container malformed and missing variables

### ISSUE THREAD

**Issue by corasaniti** [pluim003/docker-pihole-unbound#6]
unfortunately the dockercompose one-container seems to be badly formed. If I paste it into Portainer I get parse errors which I am unable to resolve. In addition, the guide refers to some variables that are not specified in the .env file

After a lot of your attempt to speed up the chriscrowe repo update, 
I hope you can help me solve these problems.
Thanks in advance

**Comment by pluim003** [comment]
Could you send me some logging? What is going wrong? Which variables should be missing? Does it work with the image from Chris?

**Comment by corasaniti** [comment]
[1665560677] unbound[828:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560677] unbound[828:0] warning: Continuing with default config settings
[1665560677] unbound[828:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665560677] unbound[828:0] fatal error: could not open ports
Stopping pihole-FTL
pihole-FTL: no process found

  [i] Time until retry: 110Starting unbound
[1665560678] unbound-checkconf[854:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560678] unbound[859:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560678] unbound[859:0] warning: Continuing with default config settings
[1665560678] unbound[859:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665560678] unbound[859:0] fatal error: could not open ports
Stopping pihole-FTL
pihole-FTL: no process found

  [i] Time until retry: 109Starting unbound
[1665560679] unbound-checkconf[885:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560679] unbound[890:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560679] unbound[890:0] warning: Continuing with default config settings
[1665560679] unbound[890:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665560679] unbound[890:0] fatal error: could not open ports
Stopping pihole-FTL
pihole-FTL: no process found

  [i] Time until retry: 108Starting unbound
[1665560680] unbound-checkconf[916:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560680] unbound[921:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560680] unbound[921:0] warning: Continuing with default config settings
[1665560680] unbound[921:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665560680] unbound[921:0] fatal error: could not open ports
Stopping pihole-FTL
pihole-FTL: no process found

  [i] Time until retry: 107Starting unbound
[1665560681] unbound-checkconf[947:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560681] unbound[952:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560681] unbound[952:0] warning: Continuing with default config settings
[1665560681] unbound[952:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665560681] unbound[952:0] fatal error: could not open ports
Stopping pihole-FTL
pihole-FTL: no process found

  [i] Time until retry: 106Starting unbound
[1665560682] unbound-checkconf[978:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560682] unbound[983:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560682] unbound[983:0] warning: Continuing with default config settings
[1665560682] unbound[983:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665560682] unbound[983:0] fatal error: could not open ports
Stopping pihole-FTL
pihole-FTL: no process found

  [i] Time until retry: 105Starting unbound
[1665560683] unbound-checkconf[1009:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560683] unbound[1014:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560683] unbound[1014:0] warning: Continuing with default config settings
[1665560683] unbound[1014:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665560683] unbound[1014:0] fatal error: could not open ports
Stopping pihole-FTL
pihole-FTL: no process found

  [i] Time until retry: 104Starting unbound
[1665560684] unbound-checkconf[1040:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560684] unbound[1045:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560684] unbound[1045:0] warning: Continuing with default config settings
[1665560684] unbound[1045:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665560684] unbound[1045:0] fatal error: could not open ports
Stopping pihole-FTL
pihole-FTL: no process found

  [i] Time until retry: 103Starting unbound
[1665560685] unbound-checkconf[1071:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560685] unbound[1076:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560685] unbound[1076:0] warning: Continuing with default config settings
[1665560685] unbound[1076:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665560685] unbound[1076:0] fatal error: could not open ports
Stopping pihole-FTL
pihole-FTL: no process found

  [i] Time until retry: 102Starting unbound
[1665560686] unbound-checkconf[1102:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560686] unbound[1107:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560686] unbound[1107:0] warning: Continuing with default config settings
[1665560686] unbound[1107:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665560686] unbound[1107:0] fatal error: could not open ports
Stopping pihole-FTL
pihole-FTL: no process found

  [i] Time until retry: 101Starting unbound
[1665560687] unbound-checkconf[1133:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560687] unbound[1138:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560687] unbound[1138:0] warning: Continuing with default config settings
[1665560687] unbound[1138:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665560687] unbound[1138:0] fatal error: could not open ports
Stopping pihole-FTL
pihole-FTL: no process found

  [i] Time until retry: 100Starting unbound
[1665560688] unbound-checkconf[1175:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560688] unbound[1180:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560688] unbound[1180:0] warning: Continuing with default config settings
[1665560688] unbound[1180:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665560688] unbound[1180:0] fatal error: could not open ports
Stopping pihole-FTL
pihole-FTL: no process found

  [i] Time until retry: 99Starting unbound
[1665560689] unbound-checkconf[1224:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560689] unbound[1229:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665560689] unbound[1229:0] warning: Continuing with default config settings
[1665560689] unbound[1229:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665560689] unbound[1229:0] fatal error: could not open ports

**Comment by corasaniti** [comment]
This is my docker-compose

version: '3.0'

services:
  pihole:
    container_name: pihole-unbound-new
    image: pluim003/pihole-unbound:latest
    hostname: pihole-unbound-raspi4-emu-bullseye
    domainname: pihole.local
    ports:
          - 8100:8100/tcp
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 5335:5335/tcp #Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    environment:
      - FTLCONF_LOCAL_IPV4=192.168.2.180
      - TZ=Europe/Rome
      - WEBPASSWORD=xxxxxxxx
      - WEBTHEME=default-light
      - REV_SERVER=false
      - WEB_PORT=8100
      - REV_SERVER:true
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC="true"
      - DNSMASQ_LISTENING=single
    volumes:
      - /home/pi/docker/pihole-unbound/pihole:/etc/pihole:rw
      - /home/pi/docker/pihole-unbound/dnsmasq:/etc/dnsmasq.d:rw
      - /home/pi/docker/pihole-unbound/unbound:/etc/unbound:rw
      - /home/pi/docker/pihole-unbound/resolv.conf:/etc/resolv.conf
    restart: unless-stopped

My raspberry IP is 192.168.2.180 and my router is Fritzbox with 192.168.2.2 IP 
Question: the file resolv.conf must be created empy?
Many Thanks

**Comment by corasaniti** [comment]
Hi,

the paths of the volumes has nothing to do with it, I can map them as I want. The problem is that it doesn't find the /etc/unbound/unbound.conf file inside the container.
I am using the one-container version.
Here is the error log

[1665564791] unbound[1506:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564791] unbound[1506:0] warning: Continuing with default config settings
[1665564791] unbound[1506:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564791] unbound[1506:0] fatal error: could not open ports
Starting unbound
[1665564792] unbound-checkconf[1515:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564792] unbound[1520:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564792] unbound[1520:0] warning: Continuing with default config settings
[1665564792] unbound[1520:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564792] unbound[1520:0] fatal error: could not open ports

  [i] Time until retry: 83Starting unbound
[1665564793] unbound-checkconf[1528:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564793] unbound[1533:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564793] unbound[1533:0] warning: Continuing with default config settings
[1665564793] unbound[1533:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564793] unbound[1533:0] fatal error: could not open ports
Starting unbound
[1665564794] unbound-checkconf[1542:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564794] unbound[1547:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564794] unbound[1547:0] warning: Continuing with default config settings
[1665564794] unbound[1547:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564794] unbound[1547:0] fatal error: could not open ports

  [i] Time until retry: 82Starting unbound
[1665564795] unbound-checkconf[1555:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564795] unbound[1560:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564795] unbound[1560:0] warning: Continuing with default config settings
[1665564795] unbound[1560:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564795] unbound[1560:0] fatal error: could not open ports
Starting unbound
[1665564796] unbound-checkconf[1569:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564796] unbound[1574:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564796] unbound[1574:0] warning: Continuing with default config settings
[1665564796] unbound[1574:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564796] unbound[1574:0] fatal error: could not open ports

  [i] Time until retry: 81Starting unbound
[1665564797] unbound-checkconf[1582:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564797] unbound[1587:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564797] unbound[1587:0] warning: Continuing with default config settings
[1665564797] unbound[1587:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564797] unbound[1587:0] fatal error: could not open ports
Starting unbound
[1665564798] unbound-checkconf[1596:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564798] unbound[1601:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564798] unbound[1601:0] warning: Continuing with default config settings
[1665564798] unbound[1601:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564798] unbound[1601:0] fatal error: could not open ports

  [i] Time until retry: 80Starting unbound
[1665564799] unbound-checkconf[1609:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564799] unbound[1614:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564799] unbound[1614:0] warning: Continuing with default config settings
[1665564799] unbound[1614:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564799] unbound[1614:0] fatal error: could not open ports
Starting unbound
[1665564800] unbound-checkconf[1623:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564800] unbound[1628:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564800] unbound[1628:0] warning: Continuing with default config settings
[1665564800] unbound[1628:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564800] unbound[1628:0] fatal error: could not open ports

  [i] Time until retry: 79Starting unbound
[1665564801] unbound-checkconf[1647:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564801] unbound[1652:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564801] unbound[1652:0] warning: Continuing with default config settings
[1665564801] unbound[1652:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564801] unbound[1652:0] fatal error: could not open ports
Starting unbound
[1665564802] unbound-checkconf[1661:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564802] unbound[1666:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564802] unbound[1666:0] warning: Continuing with default config settings
[1665564802] unbound[1666:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564802] unbound[1666:0] fatal error: could not open ports

  [i] Time until retry: 78Starting unbound
[1665564803] unbound-checkconf[1674:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564803] unbound[1679:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564803] unbound[1679:0] warning: Continuing with default config settings
[1665564803] unbound[1679:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564803] unbound[1679:0] fatal error: could not open ports
Starting unbound
[1665564804] unbound-checkconf[1688:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564804] unbound[1693:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564804] unbound[1693:0] warning: Continuing with default config settings
[1665564804] unbound[1693:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564804] unbound[1693:0] fatal error: could not open ports

  [i] Time until retry: 77Starting unbound
[1665564805] unbound-checkconf[1701:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564805] unbound[1706:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564805] unbound[1706:0] warning: Continuing with default config settings
[1665564805] unbound[1706:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564805] unbound[1706:0] fatal error: could not open ports
Starting unbound
[1665564806] unbound-checkconf[1715:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564806] unbound[1720:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564806] unbound[1720:0] warning: Continuing with default config settings
[1665564806] unbound[1720:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564806] unbound[1720:0] fatal error: could not open ports

  [i] Time until retry: 76Starting unbound
[1665564807] unbound-checkconf[1728:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564807] unbound[1733:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
[1665564807] unbound[1733:0] warning: Continuing with default config settings
[1665564807] unbound[1733:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1665564807] unbound[1733:0] fatal error: could not open ports

**Comment by pluim003** [comment]
Is unbound.conf present in  /home/pi/docker/pihole-unbound/unbound ? 

But still: is it working with the image of Chris? To fetch on cbcrowe/pihole-unbound:latest

**Comment by pluim003** [comment]
Maybe there is something with the paths, see also 
https://github.com/MatthewVance/unbound-docker/issues/21 and https://github.com/MatthewVance/unbound-docker/issues/22

**Comment by pluim003** [comment]
Glad to hear. Not all volumes are required if you don’t want to modify configs. I guess when the path isn’t there it should create it and copy the initial contents to it, if I’m not mistaken.

**Comment by pluim003** [comment]
Even thought it's solved I wanted to see if I could reproduce your 'problem' by using this docker-compose-file:

````yaml
version: '3.0'

volumes:
  etc_pihole:
  etc_dnsmasq:
#  etc_unbound:
  log_pihole:
  log_unbound:
  resolv.conf:
  usr_pihole_lists:
  ssh:

services:
  pihole:
    container_name: pihole-unbound
    image: pluim003/pihole-unbound:nightly
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - ${WEB_PORT}:${WEB_PORT}/tcp
      - 53:53/tcp
      - 53:53/udp
      # - 80:80/tcp
      - 5335:5335/tcp # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    environment:
      FTLCONF_LOCAL_IPV4: ${FTLCONF_LOCAL_IPV4}
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      WEB_PORT: ${WEB_PORT}
      REV_SERVER: ${REV_SERVER}
      REV_SERVER_TARGET: ${REV_SERVER_TARGET}
      REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
      REV_SERVER_CIDR: ${REV_SERVER_CIDR}
      PIHOLE_DNS_: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNSSEC: "true" # Enable DNSSEC
      DNSMASQ_LISTENING: single
#      DNS1: ${DNS1}
    volumes:
      - etc_pihole:/etc/pihole:rw
      - etc_dnsmasq:/etc/dnsmasq.d:rw
      - /home/pi/pi-hole/test:/etc/unbound:rw
      - log_pihole:/var/log/pihole:rw
      - log_unbound:/var/log/unbound:rw
      - ./resolv.conf:/etc/resolv.conf
      - usr_pihole_lists:/usr/local/bin/my-pihole-lists
      - ssh:/root/.ssh
    restart: unless-stopped
````

It didn't matter whether or not I had created the directory /home/pi/pi-hole/test . In both cases it would complain that /etc/unbound/unbound.conf wouldn't be found.

````bash
pihole-unbound |   [i] Preparing new gravity database...[1665591942] unbound[371:0] error: Could not open /etc/unbound/unbound.conf: No such file or directory
pihole-unbound | [1665591942] unbound[371:0] warning: Continuing with default config settings
pihole-unbound | [1665591942] unbound[371:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
pihole-unbound | [1665591942] unbound[371:0] fatal error: could not open ports
  [?] Preparing new gravity database
````


Then I thought what happens if I make a new volume:

````yaml
version: '3.0'

volumes:
  etc_pihole:
  etc_dnsmasq:
  etc_unbound_test:
  log_pihole:
  log_unbound:
  resolv.conf:
  usr_pihole_lists:
  ssh:

services:
  pihole:
    container_name: pihole-unbound
    image: pluim003/pihole-unbound:nightly
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - ${WEB_PORT}:${WEB_PORT}/tcp
      - 53:53/tcp
      - 53:53/udp
      # - 80:80/tcp
      - 5335:5335/tcp # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    environment:
      FTLCONF_LOCAL_IPV4: ${FTLCONF_LOCAL_IPV4}
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      WEB_PORT: ${WEB_PORT}
      REV_SERVER: ${REV_SERVER}
      REV_SERVER_TARGET: ${REV_SERVER_TARGET}
      REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
      REV_SERVER_CIDR: ${REV_SERVER_CIDR}
      PIHOLE_DNS_: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNSSEC: "true" # Enable DNSSEC
      DNSMASQ_LISTENING: single
#      DNS1: ${DNS1}
    volumes:
      - etc_pihole:/etc/pihole:rw
      - etc_dnsmasq:/etc/dnsmasq.d:rw
      - etc_unbound_test:/etc/unbound:rw
      - log_pihole:/var/log/pihole:rw
      - log_unbound:/var/log/unbound:rw
      - ./resolv.conf:/etc/resolv.conf
      - usr_pihole_lists:/usr/local/bin/my-pihole-lists
      - ssh:/root/.ssh
    restart: unless-stopped
````

And start it:

````bash
pi@raspberrydick:~/pi-hole $ docker-compose up
WARNING: The DOMAIN_NAME variable is not set. Defaulting to a blank string.
Creating volume "pi-hole_etc_unbound_test" with default driver
Recreating pihole-unbound ... done
Attaching to pihole-unbound
````

Then indeed the default contents from /etc/unbound will be copied to this volume and will use then the default configs.
So went back to my original docker-compose and use my modified configfiles.
This is actually the 'best' way to do. Because if in your case you want to make modifications to unbound.conf (or the files in unbound.conf.d) then they  will be overwritten next time you recreate/restart the container.

That's why I also use volumes for the logfiles. As after a restart you want or need to look in an older logfile you can't as it's gone.
And I prefer the volumes not in my home-drive but somewhere under /var/lib/docker. Then you won't accidentally delete or modify stuff as you need root-permissions.

And in my case I use port 8100, as I have other stuff running. I have more dockercontainers and use nginx to be able to access stuff from outside the house by using https://pihole.mydomain.whatever.
